# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c126f41c64d5c263defc7c5c5d4f129ce4c92a0b2ca21bdba634a2e2ef5832f19c6ff76972924b87ccb451d18a27c9238c00a8fea78dafe7bccd9a4e34539798

test:
  secret_key_base: 0c66e775658fb2246e0f4e1c5427bc1ef26ab0499093af417e29842612b0e80abc0b60fea17ecb613ebe8fc06b892fd753472cdac1a759b698f269f3b219532f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
